import type { Metadata } from "next";
import { Roboto, Roboto_Mono } from "next/font/google";
import { GlobalStyles } from "@/styles/global";
import "./globals.css";
import { GetCssText } from "@/utils/get-css-text-wrapper";
import { SessionProvider } from "next-auth/react";
import Head from "next/head";
import { Providers } from "./providers";
import { getServerSession } from "next-auth";
import { authOptions } from "./api/auth/[...nextauth]/route";

const robotoSans = Roboto({
  variable: "--font-roboto-sans",
  subsets: ["latin"],
});

const robotoMono = Roboto_Mono({
  variable: "--font-roboto-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions);

  return (
    <html lang="pt-BR">
      <Head>
        <GetCssText />
      </Head>
      <body
        className={`${robotoSans.variable} ${robotoMono.variable} antialiased`}
      >
        <GlobalStyles />
        <Providers session={session}>{children}</Providers>
      </body>
    </html>
  );
}
