import type { Metadata } from "next";
import { Roboto, Roboto_Mono } from "next/font/google";
import { GlobalStyles } from "@/styles/global";
import "./globals.css";
import { GetCssText } from "@/utils/get-css-text-wrapper";

const robotoSans = Roboto({
  variable: "--font-roboto-sans",
  subsets: ["latin"],
});

const robotoMono = Roboto_Mono({
  variable: "--font-roboto-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <GetCssText />
      <body
        className={`${robotoSans.variable} ${robotoMono.variable} antialiased`}
      >
        <GlobalStyles />
        {children}
      </body>
    </html>
  );
}
